version: "2"

services:
  prometheus:
    image: prom/prometheus:v2.17.1
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/volumes/data:/prometheus

  grafana:
    image: grafana/grafana:6.7.2
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/volumes/data:/var/lib/grafana

  telegraf:
    image: telegraf:1.14.1
    depends_on:
      - prometheus
    ports:
      - 8125:8125/udp
      - 9273:9273
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
      - /var/run/docker.sock:/var/run/docker.sock

  statsd-exporter:
    image: prom/statsd-exporter:v0.15.0
    ports:
      - 9102:9102
      - 9125:9125
      - 9125:9125/udp
